DROP TABLE IF EXISTS `game` CASCADE;

CREATE TABLE `game` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`game_Title` VARCHAR(255) NOT NULL,
	`genre` VARCHAR(255) NOT NULL,
	`publisher` VARCHAR(255) NOT NULL,
	`platform` VARCHAR(255) NOT NULL,
	`release_Year` VARCHAR(255) NOT NULL
);